version: '3'

services:
    mssql:
        container_name: azure_db1
        image: mcr.microsoft.com/azure-sql-edge:latest
        networks:
          - test
        ports:
          - "1433:1433"
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: "*8b5T@K07iGx"

networks:
  test:
    driver: bridge

volumes:
    mssql-azuresql-edge-data:
    sqlpad-volume:
